from fpdf import FPDF
import pandas as pd
import os

pdf = FPDF()
pdf.set_auto_page_break(auto=True, margin=15)

# Add TTF Unicode font
pdf.add_page()
pdf.add_font("DejaVu", "", "DejaVuSans.ttf", uni=True)
pdf.set_font("DejaVu", "B", 18)
pdf.multi_cell(0, 10, "Enzymatic Kinetics Analysis Report", align="C")
pdf.ln(10)

pdf.set_font("DejaVu", "", 12)
pdf.multi_cell(0, 8, "Generated by Oluwaseun O. Ajayi | Chemistry PhD Researcher\n\n"
                      "This report includes IC50 analysis with replicates, "
                      "Michaelis–Menten batch fitting, and publication-quality plots.", align="L")

# IC50 Results
ic50_file = "results/batch_ic50_with_reps_results.csv"
if os.path.exists(ic50_file):
    results_ic50 = pd.read_csv(ic50_file)
    pdf.add_page()
    pdf.set_font("DejaVu", "B", 14)
    pdf.cell(0, 10, "IC50 Results with Replicates", ln=True)
    pdf.set_font("DejaVu", "", 12)
    for idx, row in results_ic50.iterrows():
        line = (f"{row['Inhibitor']}: Bottom={row['Bottom']:.2f}, Top={row['Top']:.2f}, "
                f"IC50={row['IC50']:.2f}, Hill={row['Hill']:.2f}")
        pdf.multi_cell(0, 8, line)

# Michaelis-Menten Results
mm_file = "results/batch_kinetics_results.csv"
if os.path.exists(mm_file):
    results_mm = pd.read_csv(mm_file)
    pdf.add_page()
    pdf.set_font("DejaVu", "B", 14)
    pdf.cell(0, 10, "Michaelis–Menten Batch Results", ln=True)
    pdf.set_font("DejaVu", "", 12)
    for idx, row in results_mm.iterrows():
        line = (f"{row.get('enzyme','Unknown')} | Condition: {row.get('condition','NA')} | "
                f"Vmax={row.get('Vmax',0):.2f}, Km={row.get('Km',0):.2f}")
        pdf.multi_cell(0, 8, line)

# Add Figures
pdf.add_page()
pdf.set_font("DejaVu", "B", 14)
pdf.cell(0, 10, "Figures", ln=True)
for fig in sorted(os.listdir("figures")):
    if fig.endswith(".png"):
        pdf.add_page()
        pdf.image(os.path.join("figures", fig), x=10, y=20, w=180)

# Save PDF
output_file = "results/enzymatic_kinetics_report.pdf"
pdf.output(output_file)
print(f"✅ PDF report generated: {output_file}")
